//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
namespace GeneralPackage.GameData
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using GeneralPackage.Controller;

	public class AgentBaseClass
	{

        public virtual void ready () {
        }

        public virtual void deleted()
        {
            //TODO: дописать связь с контроллером
        }

        public virtual void setController(ControllerSet set)
        {

        }

        #region StepByStep model

        public virtual void makeTurn()
        {
                
        }
        #endregion

    }
}

