//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
namespace GeneralPackage.GameData
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using GeneralPackage.Structures;

	public class AgentList
	{
        private Dictionary<int,Agent> list = new Dictionary<int,Agent>();

        private Performer.CommandPerformer performer;
        
        #region setters

        public void setPerformer(Performer.CommandPerformer performer_)
        {
            performer = performer_;
        }

        #endregion


        #region indexator

        int lastCandidate = 1;
        private int getNewIndex()
        {
            for (int i = lastCandidate; i < int.MaxValue; i++)
            {
                if (!list.ContainsKey(i))
                {
                    lastCandidate = i + 1;
                    return i;
                }
            }
            throw new Exception("AgentList is full and contains " + list.Count.ToString() + " elements.");
        }

        #endregion

        #region agent delete

        private void deleteAgent(int id)
        {
            if (list.ContainsKey(id))
            {
                list.Remove(id);
                lastCandidate = Math.Min(lastCandidate,id);
            }
        }

        public void delAgent(int id)
        {
            deleteAfter(id);
        }

        #endregion

        #region stepByStep Model

        #region stackDelete

        private List<int> toDelete = new List<int>();

        public void deleteAfter(int id)
        {
            list[id].deleted();
            toDelete.Add(id);
        }

        private void completeDelete()
        {
            foreach (int id in toDelete)
            {
                deleteAgent(id);
            }
            toDelete.Clear();
        }

        #endregion

        public void launchAgents()
        {
            foreach (Agent ag in list.Values)
            {
                performer.newTurn();
                ag.Eventer.makeTurn();
            }
            completeDelete();
        }

        public IReadOnlyDictionary<int, Agent> getDictionary()
        {
            return list;
        }

        

        internal Agent this[int i]
        {
            get { return list[i]; }
        }

        #endregion

        #region adding Agents

        public int addCustomAgent(Coord startCoord, AgentBaseClass eventHandler,
                                    double speed, double viewRadius)
        {
            int i = getNewIndex();
            list.Add(i, new Agent(eventHandler, i, speed, viewRadius, startCoord, AgentType.CommonSearcher, AgentState.Common));
            return i;
        }
        public int addCustomAgent(Coord startCoord, AgentBaseClass eventHandler,
                                   double speed, double viewRadius, AgentType agentType, AgentState state)
        {
            int i = getNewIndex();
            list.Add(i, new Agent(eventHandler, i, speed, viewRadius, startCoord, agentType, state));
            return i;
        }

        public void addTestAgent()
        {
            int i = getNewIndex();
            list.Add(i, new Agent(new AgentBaseClass(), i, 0.0, 0.1, Coord.rand(),AgentType.Dummy, AgentState.Common));
        }

        #endregion

        #region Agents state

        public AgentCutaway getAgentCutaway(int ID)
        {
            return list[ID].getCutaway();
        }

        public void setAgentState(int ID,AgentState state)
        {
            list[ID].state = state;
        }

        #endregion
    }
}

