//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
namespace GeneralPackage.Controller
{
	using GeneralPackage.Performer;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using Structures;

	public class AgentController : IWalker, ISensor, ISearcher
    {

        #region attributes
        private  CommandPerformer performer
		{
			get;
			set;
        }

        private int ID
        {
            get;
            set;
        }

        #endregion

        #region constructor

        public AgentController(CommandPerformer cp, int agentID)
        {
            performer = cp;
            ID = agentID;
        }

        #endregion

        #region IWalker

        bool IWalker.makeStep(Coord direction, double speedPercent)
        {
            return performer.makeStep(direction, speedPercent, ID);
        }
        bool IWalker.makeStep(Coord direction)
        {
            return performer.makeStep(direction, ID);
        }


        #endregion

        #region ISensor

        AgentCutaway[] ISensor.agentsAround()
        {
            return performer.agentsAround(ID);
        }

        Coord ISensor.myPosition()
        {
            return performer.agentPosition(ID);
        }

        #endregion

        #region ISearcher

        bool ISearcher.grabObject(int objID)
        {
            return performer.grabObject(ID, objID);
        }

        #endregion



    }
}

