//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
namespace GeneralPackage.Controller
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using Structures;

	public interface IWalker 
	{
        bool makeStep(Coord direction, double speedPercent);

        bool makeStep(Coord direction);

	}
}

