//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
namespace GeneralPackage.Structures
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public struct AgentCutaway
	{
		public int ID
		{
			get;
			set;
		}

		public Coord coord
		{
			get;
			set;
		}

		public AgentType type
		{
			get;
			set;
		}

        public AgentState state
        {
            get;
            set;
        }

	}
}

