//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
namespace GeneralPackage.Structures
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public static class Average
	{
        public static double speed = 0.02;
        public static double viewRadius = 0.05;
	}
}

