//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
namespace GeneralPackage.Structures
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    public struct Coord
    {
        private static Random random = new Random();

        #region attributes


        public double x
        {
            get {return X;}
            set {X = value;}
        }

        public double y
        {
            get { return Y; }
            set { Y = value; }
        }

        private double X;
        private double Y;

        #endregion

        #region constructor

        public Coord(double x_, double y_) 
        {
            X = x_;
            Y = y_;
        }
            

        #endregion

        public static Coord rand()
        {
            return new Coord
            {
                x = random.NextDouble(),
                y = random.NextDouble()
            };
                
        }

        public static Coord operator +(Coord a, Coord b)
        {
            return new Coord(a.x + b.x, a.y + b.y);
        }

        public static Coord operator -(Coord a, Coord b)
        {
            return new Coord(a.x - b.x, a.y - b.y);
        }

        public override string ToString()
        {
            return "( " + x.ToString() + " , " + y.ToString() + ")";
        }

        public bool inField()
        {
            return (x <= 1.0 && x >= 0.0 && y <= 1.0 && y >= 0.0);
        }

        public double norm()
        {
            return Math.Sqrt(x * x + y * y);
            }


    }
}